      - name: Compile and run all C programs
        run: |
          mkdir -p out
          found=false
          for f in $(find . -name "*.c"); do
            found=true
            prog=$(basename "$f" .c)
            dir=$(dirname "$f" | sed 's|./||')
            outdir="./out/${dir}_${prog}"
            mkdir -p "$outdir"

            echo "Compiling $f ..."
            gcc "$f" -o "$outdir/$prog" 2> "$outdir/compile_err.txt" || true

            if [ -x "$outdir/$prog" ]; then
              echo "Running $prog ..."
              timeout 5 "$outdir/$prog" > "$outdir/program_output.txt" 2>&1 || echo "Program ended with non-zero exit" >> "$outdir/program_output.txt"
            else
              echo "Compilation failed, see compile_err.txt" > "$outdir/program_output.txt"
            fi
          done

          if [ "$found" = false ]; then
            echo "⚠️ No .c files found in repository" > out/NO_FILES_FOUND.txt
          fi

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: lab-results
          path: out/
