name: Compile and Run C Programs

on:
  push:
    paths:
      - '**/*.c'
  workflow_dispatch:   # allows manual run from Actions tab

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compile and run all C programs
        run: |
          mkdir -p out
          for f in $(find . -name "*.c"); do
            prog=$(basename "$f" .c)
            dir=$(dirname "$f" | sed 's|./||')
            outdir="./out/${dir}_${prog}"
            mkdir -p "$outdir"

            echo "Compiling $f ..."
            gcc "$f" -o "$outdir/$prog" 2> "$outdir/compile_err.txt" || true

            if [ -x "$outdir/$prog" ]; then
              echo "Running $prog ..."
              timeout 5 "$outdir/$prog" > "$outdir/program_output.txt" 2>&1 || echo "Program ended with non-zero exit" >> "$outdir/program_output.txt"
            else
              echo "Compilation failed, see compile_err.txt" > "$outdir/program_output.txt"
            fi
          done

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: lab-results
          path: out/
